# Welcome to Jekyll!
#
# This was created using jekyll new ovrdc-wiki - I have updated some of the settings and hashed out others
# I am using the pavillion css framework and based this site on their demo page at www.pavilio.io
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FOSS4G 2017
#email: your-email@domain.com
description: >-
  These are my own personal notes from the International FOSS4G Conference in Boston, August 2017.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: getbounds
#github_username:  jekyll

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:title/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "main"

#css styles lazy sass
font-color--secondary: "black" #original #737373
font-color--main: "#333"
font-color--link-active: "#9a2900" #005ab3 & #0080ff
font-color--highlight: "#c53500"
font-color--highlight2: "#c53500" #0080ff
font-color--highlight2-button: "#c53500 " #0066cc
font-color--highlight2-button-active: "#9a2900 " #0061c2
header-img: header2.png
